server:
  port: 20006
  servlet:
    context-path: / #访问路径
    
#spring:
#  # mysql 配置
#  datasource:
#    username: root #用户名
#    password: 123456 #用户密码
#    driver-class-name: com.mysql.cj.jdbc.Driver #数据源
#    url: jdbc:mysql://120.46.200.237:20001/voice-ai-cc?serverTimezone=Asia/Shanghai&useTimezone=true&useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true #连接地址
#    type: com.zaxxer.hikari.HikariDataSource #连接池类型
#
#  #reids配置
#  redis:
#    host: 120.46.200.237:20002 # Redis服务器地址
#    password: 123456 # Redis服务器连接密码(默认为空)
#    timeout: 120000 # 连接超时时间(毫秒)
#
#
## mybatis-plus配置
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml #读取mapper的映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl #不打印日志

# 日志路径配置
logging:
  file:
    path: /Users/chenjia/logs